apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-vault
  source:
    path: production/patch
    repoURL: https://github.com/lanbingcloud/demo-vault-kubernetes.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
